Cron task manager
OPUS4/application pull request #1040
Opened 2023-06-08 08:02 UTC by haogatyp

2023-07-06 08:14 UTC, j3nsch requested changes
Wir müssen uns übelegen, wie das jetzt weiter geht. Vielleicht können wir ja schon Verbesserungen in die 4.8.1 aufnehmen.

2023-07-06 12:05 UTC, haogatyp commented on composer.json
> +      "kylekatarnls/update-helper": true
Nach meinem Verständnis ist das nicht notwendig. Ich habe es deshalb entfernt.

2023-07-06 16:36 UTC, haogatyp commented on scripts/common/bootstrap.php
> +            APPLICATION_PATH . '/application/configs/tasks.ini',
tasks.ini wird jetzt nur noch innerhalb des Task-Schedulers gelesen.

2023-07-06 16:39 UTC, haogatyp commented on library/Application/Task/TaskScheduler.php
> +        $cronScript = APPLICATION_PATH . "/" . $config->cron->taskRunner;
Wird jetzt als absoluter Pfad in der application.ini definiert.

2023-07-14 16:51 UTC, haogatyp commented on crunz.yml
> +timezone: Europe/Berlin
Ja, jede Instanz hat ihre eigene crunz.yaml

2023-07-20 11:07 UTC, j3nsch reviewed
Vielen Dank! Ein paar Kleinigkeiten sollten zur besseren Verständlichkeit noch angepasst werden.

2023-07-20 11:07 UTC, j3nsch commented on library/Application/Task/TaskScheduler.php
> +    public function run()
Muss nicht `run` heißen, oder? Was macht die Funktion?

2023-07-20 11:07 UTC, j3nsch commented on library/Application/Task/TaskScheduler.php
> +            $log->err("Could not read the task runner path from 'application.ini'");
`application.ini` ist keine Information, die Du hier haben kannst. Die Konfiguration kann irgendwo her kommen. Im Augenblick sind es mehrere INI Dateien, darunter `application.ini`. Das kann sich ändern.

2023-07-20 11:07 UTC, j3nsch commented on library/Application/Task/TaskScheduler.php
> +        if (! is_readable($config->cron->taskRunner)) {
Verwende mal bitte ruhig lokale Variablen, um nicht immer wieder durch PHP-Magic auf die Optionen zuzugreifen.

2023-07-21 07:18 UTC, j3nsch commented on library/Application/Task/TaskConfigReader.php
> +                $class->implementsInterface(Application_Task_TaskInterface::class) ||
Da müssen wir noch mal drüber nachdenken. Warum zwei Interfaces?

2023-07-21 07:22 UTC, j3nsch commented on tests/library/Application/Task/TaskConfigReaderTest.php
> +        $taskConfig->setEnabled(true);
Mach das Interface von `TaskConfig` mal bitte fluent, so dass man die set-Calls verketten kann. Außerdem macht es Sinn, denke ich, das Mapping vom Array in die Klasse zu verlagern. Die Umwandlung in ein Array brauchen wir im Augenblick nicht.

2023-07-21 07:32 UTC, j3nsch commented on tests/library/Application/Task/TaskConfigReaderTest.php
> +        $taskConfig->setClass("Application_Job_SendNotificationJob");
Bitte Klassen immer über `NAME::class` referenzieren und nicht über String-literals. Wenn sich die Klassennamen später ändern, verkompliziert das sonst den Prozess.

2023-07-21 09:41 UTC, haogatyp commented on library/Application/Task/TaskScheduler.php
> +    public function run()
Initialisiert ja eigentlich den Crunz-Scheduler und gibt diesen dann für die Crunz-Task zurück. Haebe es daher in init() umbenannt.

2023-07-21 09:41 UTC, haogatyp commented on library/Application/Task/TaskScheduler.php
> +            $log->err("Could not read the task runner path from 'application.ini'");
Habe ich herausgenommen.

2023-07-21 09:42 UTC, haogatyp commented on library/Application/Task/TaskScheduler.php
> +        if (! is_readable($config->cron->taskRunner)) {
Habe ich so gemacht.

2023-07-21 17:05 UTC, haogatyp commented on tests/library/Application/Task/TaskConfigReaderTest.php
> +        $taskConfig->setClass("Application_Job_SendNotificationJob");
Umgesetzt

2023-07-21 17:06 UTC, haogatyp commented on tests/library/Application/Task/TaskConfigReaderTest.php
> +        $taskConfig->setEnabled(true);
Erledigt

2023-07-21 17:06 UTC, haogatyp commented on library/Application/Task/TaskConfigReader.php
> +                $class->implementsInterface(Application_Task_TaskInterface::class) ||
Wie besprochen habe ich das JobInterface entfernt und durch das TaskInterface ausgetauscht.

2023-07-21 17:07 UTC, haogatyp commented on tests/crunz/tasks.ini
> +crontasks.dummyTask2.schedule = "*/2 * * * *"
Sollte erledigt sein.

2023-07-21 17:08 UTC, haogatyp commented on tests/crunz/crunzTest.php
> +*/
Hier gibt es weiterhin Probleme mit der Ausführbarkeit des Skripts im Zusammenhang mit dem Bootstrapping. Ich habe es erstmal ensprechend im Script dokumentiert.

2023-07-21 17:09 UTC, haogatyp commented on library/Application/Task/TaskConfigReader.php
> +        $fileName = isset($config->cron->configFile) && $config->cron->configFile ? $config->cron->configFile : '';
Stimmt, ist geändert.

2023-07-21 17:10 UTC, haogatyp commented on library/Application/Task/TaskConfigReader.php
> +     * Returns the task configuration from the task ini file.
Ist umbenannt, zusätzlich ist der TaskScheduler jetzt entfernt und dessen Code in den TaskManager übernommen worden.

2023-07-27 06:44 UTC, j3nsch commented on library/Application/Task/TaskInterface.php
> +/*
This should be part of the class comment.

2023-07-28 08:36 UTC, j3nsch commented
Fix mal bitte noch den Konflikt in `composer.json` und schau Dir die Crunz Abhängigkeit an. Die Version muss flexibler angegeben werden, so dass für PHP 7.1 eine passende Version genommen werden kann. Wir haben den PHP 7.1 Support noch nicht beendet.

2023-07-28 08:57 UTC, j3nsch commented
Für Crunz-Kompatibilität mit PHP 7.1 muss man sehr weit zurück gehen, zu eine 1.x Version. Können wir sagen, ob es damit immer noch funktioniert? Ansonsten müssen wir sagen, dass die Crunz-Funktionaltität nur mit PHP 8 bzw ab 7.4 funktioniert. Dann muss aber `composer.json` immer noch so sein, dass man OPUS 4 mit PHP 7.1 betreiben kann. Momentan gibt es ja ein Problem beim installieren der Dependencies.

2023-08-15 13:07 UTC, j3nsch approved these changes
Danke. Bei der Umstellung auf `OutputInterface`, ist das eine oder andere `PHP_EOL` bzw. `\n` drin geblieben, aber das kann später mal gefixt werden.

2023-08-15 13:55 UTC, merged