#1035, #1048, #1059: confgurable CSV export, revised DOI import, new document type labels
OPUS4/application pull request #1060
Opened 2023-06-29 13:30 UTC by alw-bsz

- Implements configurable CSV export and revised metadata import based on Crossref DOIs
- Updates document type labels to Gemeinsames Vokabular 2.0

2023-06-29 15:09 UTC, j3nsch requested changes
Vielen Dank! Ich die Änderungen überflogen und ein paar Kommentare geschrieben. Generell sollte keine Tabs verwendet werden. Auch in Dateien, bei denen es nicht durch die Formatierung auffällt, stecken jetzt Tabs drin. 

Bitte den einen Unit Test, der bislang gebrochen ist, fixen. Es muss nur ein Buchstabe geändert werden. Dann können wir sehen, ob es noch weitere Probleme gibt.

Die umfangreichen Änderungen beim CSV-Export sollten durch Tests abgedeckt werden, aber das ist im Augenblick nicht machbar. Ich hoffe, dass die Änderungen keinen negativen Effekt für die bisherige Funktionalität haben.

Für diese Änderungen sollten Bemerkungen in RELEASE_NOTES.md geschrieben werden. Das sollte in diesem Fall vom BSZ kommen.

Es wäre gut für unterschiedliche Themen separate PRs zu verwenden. Ansonsten kann es passieren, dass Änderungen, wie für das Gemeinsame Vokabular 2.0, nicht übernommen werden können, weil an anderen, unabhängigen Änderungen noch gearbeitet werden muss.

2023-06-30 09:05 UTC, bfalkenstein commented on application/configs/doctypes_templates/doi.phtml
> +            <span id="invisible_formfield">
Ok, wird geändert in `id="doi_import_invisible_field"`

2023-06-30 09:05 UTC, bfalkenstein commented on modules/export/models/XmlExport.php
> +			'translate'
Ok

2023-06-30 09:05 UTC, bfalkenstein commented on modules/default/language/fieldnames.tmx
> +		<tu tuid="Language">
Ok

2023-06-30 09:06 UTC, bfalkenstein commented on db/masterdata/018_create_enrichmentkeys.sql
> +-- 'ConferenceTitle': "Name der Konferenz", s.o.
Ok

2023-06-30 09:07 UTC, bfalkenstein commented on modules/export/views/scripts/stylesheets/utils/csv_utils.xslt
> + * @category    Application
Ok, wird geändert in 
```* along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2023, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */```

2023-06-30 09:08 UTC, bfalkenstein commented on modules/export/views/scripts/stylesheets/utils/csv_utils.xslt
> +
Ok

2023-06-30 09:13 UTC, bfalkenstein commented on modules/export/views/scripts/stylesheets/csv.xslt
> + * @category    Application
Ok, in diesem Fall dann die Zeitspanne, also
```* Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2010-2023, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */```
 Richtig?

2023-06-30 09:19 UTC, bfalkenstein commented
@j3nsch, zu dem Unit Test Fehler: Wie kann ich denn sehen, an welcher Stelle im Code dieser Fehler 'article' <-> 'Article' steht? (Ich kenne mich nicht mit Unit Tests aus)

2023-06-30 12:29 UTC, j3nsch commented on modules/export/views/scripts/stylesheets/csv.xslt
> + * @category    Application
Zeitspannen machen wir nicht mehr. Das hat eigentlich nie Sinn gemacht. Also nur 2010 bzw. das Jahr in dem die Datei angelegt wurde. Danke!

2023-06-30 12:32 UTC, j3nsch commented
> @j3nsch, zu dem Unit Test Fehler: Wie kann ich denn sehen, an welcher Stelle im Code dieser Fehler 'article' <-> 'Article' steht? (Ich kenne mich nicht mit Unit Tests aus)

Im Testreport (https://github.com/OPUS4/application/actions/runs/5412802147/jobs/9837414361?pr=1060) kann man sehen, welcher Test fehlgeschlagen ist.

    Application_View_Helper_DcTypeTest::testDcType
    
Ich vermute Du kannst den Report nicht sehen, weil Du bisher nicht zur Organisation gehörst und auch noch nicht als Collaborator registriert bist.

2023-06-30 12:52 UTC, j3nsch commented
In den Commit Nachrichten können die Issue Nummern angegeben werden. Das ermöglicht später eine Zuordnung. Das ist immer wieder nützlich, wenn herausgefunden werden muss warum einzelne Änderungen gemacht worden sind. Also bitte nach Möglichkeit die Nachrichten immer mit der Nummer anfangen, z.B. "#1035" .

2023-06-30 15:53 UTC, bfalkenstein commented on modules/export/views/scripts/stylesheets/csv.xslt
> + * @category    Application
Sorry, der PR war schon abgeschickt. Ich merk's mir.

2023-07-03 05:57 UTC, j3nsch commented
Es ist nicht nur "beautifying". :-) Ein einheitlicher Coding Style, macht den Code lesbarer, spart Zeit und reduziert Bugs. Mit `composer cs-check` kann man das lokal vorab prüfen und mit `composer cs-fix` die reinen Formatierungsprobleme automatisch fixen lassen, z.B. Einrückungen und Kommas am Ende von Arrays.

2023-07-03 10:23 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Hat sich die Datei wirklich verändert oder sind nur die Zeilenenden anders?

2023-07-03 10:38 UTC, alw-bsz commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Die Datei hat sich tatsächlich verändert, z.B. ist ab Zeile 2725 eine ganze Reihe an neuen Sprachen aufgenommen worden.

2023-07-03 10:40 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Okay, dann übernehme ich das erst einmal. Die Dateien wurden direkt von der DNB übernommen? Es sind anscheinend Tabs drin. Ob die Zeilenenden für OPUS 4 richtig sind, kann ich auf GitHub nicht erkennen, aber bei dieser Datei haben sie sich anscheinend geändert.

2023-07-03 10:41 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Wenn die Datei nicht für OPUS 4 editiert wurden, bin ich geneigt sie im Original zu übernehmen.

2023-07-03 10:46 UTC, alw-bsz commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Ja, ich habe die Dateien direkt von der DNB übernommen. Ich habe keine Anpassungen für OPUS 4 vorgenommen. Ich kann sie natürlich an den OPUS4 Coding Style anpassen, wenn nötig.

2023-07-03 10:47 UTC, alw-bsz commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Eine andere Frage ist für mich noch, wie wir mit XSDs verfahren, die wir noch in OPUS mitführen, aber nicht mehr von der DNB ausgeliefert werden. Kann ich die löschen oder sollen sie wegen der Abwärtskompatibilität beibehalten werden?

2023-07-03 10:48 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Nein, dann übernehmen wir sie so wie sie sind. Es ist ja im Prinzip nicht unser Code.

2023-07-03 10:56 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Ich weiß nicht mal, ob es gut war die Dateien zu löschen die hier PR schon gelöscht wurden. Natürlich sollten wir Altlasten beseitigen und es wäre mindestens sinnvoll dafür ein Issue anzulegen und die Löschkandidaten aufzulisten. Ich kann aber nicht sagen wie die Dateien in einzelnen Instanzen genutzt werden. Daher sollte zumindest von beiden Hosting-Team ein "Okay" kommen. Um Selbstbetreibern eine Chance für Einsprüche zu geben, sollten wir die Löschungen erst einmal nur Ankündigen, als etwas das in kommenden Releases erfolgen wird.

Wenn das Dateien sind, die sozusagen nur von den DNB Dateien verwendet werden, also zur "internen" Struktur des "Codes" gehören, den wir von der DNB einfach übernehmen, können die Dateien aus meiner Sicht auch jetzt schon gelöscht werden. Vielleicht wäre für diese Aktualisierung ein separates Ticket sinnvoll gewesen oder steht das in direktem Zusammenhang mit #1048 und kann dort mit dokumentiert werden?

Dieser PR umfasst definitiv zu viele Themen. Ideal ist immer nur ein Thema pro PR.

2023-07-03 10:58 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Schreibt Ihr noch was in die RELEASE_NOTES.md? Insbesondere für die CSV Geschichte wäre das wichtig. Natürlich nur ein kleiner Hinweis mit Verweis auf den Ort wo man weitere Informationen finden kann.

2023-07-03 11:08 UTC, merged

2023-07-03 11:08 UTC, j3nsch commented
Änderungen wurde übernommen, damit der PR nicht noch größer wird.

2023-07-03 11:11 UTC, j3nsch commented
Ich werde die Änderungen vom Branch **issue1045** nach **v4.8.1** übernehmen. Alle weiteren Änderungen bitte als neue PRs dorthin.

2023-07-03 15:06 UTC, bfalkenstein commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Die RELEASE_NOTES.md ist ergänzt. https://github.com/OPUS4/application/compare/v4.8.1...bfalkenstein:application:patch-1 
Ich hoffe der Link zum userdoc ist richtig?

2023-07-03 15:46 UTC, j3nsch commented on tests/resources/xmetadissplus/iso639-2.xsd
> -<?xml version="1.0" encoding="UTF-8"?>
Danke. Der Link sollte stimmen. Die veröffentlichte Dokumentation wird erst zum Release aktualisiert. Dieser PR hier ist schon abgeschlossen. Der Branch existiert nicht mehr. Es ist neuer PR notwendig, direkt auf `v4.8.1`. Ich habe das erledigt und die Änderung übernommen.