Oai sets refactoring
OPUS4/application pull request #1122
Opened 2023-10-20 07:19 UTC by haogatyp

2023-11-07 17:36 UTC, j3nsch requested changes
Vielen Dank! Das ist erst einmal alles was mir noch aufgefallen bzw. eingefallen ist.

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/DocumentTypeSets.php
> + * Class for the "document type" set type
Bitte auch festhalten, dass der DC-Type verwendet wird.

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/DocumentTypeSets.php
> +                $sets[$setSpec] = ucfirst($dcType);
Ich gehe davon aus, dass das im alten Code so funktioniert hat. Die Zahl der Dokumenttypen erhöht sich aber gerade und es kann durchaus sein, dass mehrere OPUS 4-Dokumenttypen auf den gleiche DC-Type gemappt werden. Das kann zumindest nicht ausgeschlossen werden. Darüber müssen wir noch mal nachdenken.

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/DocumentTypeSets.php
> +        // TODO Behavior with invalid set names should be reconsidered.
Kann man dazu noch mehr sagen? Warum und wohin?

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/DocumentTypeSets.php
> +                'Invalid set name: ' . implode(':', $setName->getSetParts())
Könnte die `SetName`-Klasse nicht eine Funktion haben, die den vollständigen Namen zurück gibt? Die "Rekonstruktion" außerhalb sollte nicht notwendig sein, wenn wir dafür schon eine extra Klasse haben.

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/SetName.php
> +class Oai_Model_Set_SetName
Könnte noch ausgebaut werden, oder? Validierung, vollständigen Namen zurück geben, ...?

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/SetsManager.php
> +     * Returns all oai sets.
Nicht kritisch, aber bitte immer OAI (außer in Klassennamen).

2023-11-07 17:36 UTC, j3nsch commented on tests/modules/oai/controllers/IndexControllerTest.php
> +    {
@alw-bsz Was meint Ihr zu dem bisherigen Verhalten, dass hier jetzt noch mal explizit durch Tests festgehalten wurde? Bei Collection-Sets mit ungültigen Set, drei Teile, kommt eine richtige Exception, während bei den anderen Set-Typen ein "noRecordsMatch" kommt.

2023-11-07 17:36 UTC, j3nsch commented on tests/modules/oai/models/Set/BibliographySetsTest.php
> +    }
Für alle Set-Typen wäre es sicherlich sinnvoll die `configureFinder` Funktion zu testen. Man müsste die eigentlich Suchergebnisse prüfen, was aufwendig ist. Bitte zumindest Incomplete-Test dazu hinzufügen. Der Kommentar bezieht sich auf alle SetType-Klassen. Danke!

2023-11-07 17:36 UTC, j3nsch commented on modules/oai/models/Set/SetName.php
> +class Oai_Model_Set_SetName
Die Klasse sollte Tests bekommen.

2023-11-07 17:36 UTC, j3nsch commented on tests/modules/oai/models/Set/SetsManagerTest.php
> +        $this->assertEquals(69, count($sets));
Die Zahl der Sets wird sich immer wieder ändern, da wir mit einer befüllten Datenbank testen. Vielleicht könnte man die unterschiedlichen Typen gezielt testen.

2023-11-07 17:36 UTC, j3nsch commented on tests/modules/oai/models/Set/SetsManagerTest.php
> +        $this->assertEquals(69, count($sets));
Man könnte mehrere Tests haben, in denen die Konfiguration manipuliert wird, um auch diesen Aspekt zu prüfen und die Ergebnisse vielleicht weniger anfällig für Änderungen zu machen. Man könnte im Test die Zahl der verwendeten Dokumenttypen direkt mit dem Finder holen und damit die Set-Generierung prüfen. Macht das Sinn?

2023-11-08 09:53 UTC, alw-bsz commented on tests/modules/oai/controllers/IndexControllerTest.php
> +    {
Das finde ich zumindest merkwürdig. In beiden Fällen wird ja ein Set als "Suchterm" verwendet, das es nicht gibt. Dann sollte sich OPUS eigentlich auch identisch verhalten.

2023-11-10 11:10 UTC, haogatyp commented on tests/modules/oai/controllers/IndexControllerTest.php
> +    {
Bei den 3-teiligen sets verhält es sich jetzt gleich. Bei CollectionSets gibr es im Code aber noch Stellen, an denen Sets/Subsets für die es keine CollectionRole/Collection gibt als ungültig definiert werden. Das habe ich zunächst so belassen, habe aber den Exceptions einen OAI-Error-Code hinzugefügt (badArgument). Dadurch kommt es in diesen Fällen zumindest nicht mehr zu einer harten Exception am Ende, sondern zu einer OAI-Fehlermeldung.
Wäre es vielleicht besser dort auch, mit noRecordsMatch zu reagieren, zumindes für die Fälle in denen das Set formal valide ist?

2023-11-10 12:33 UTC, j3nsch commented on tests/modules/oai/controllers/IndexControllerTest.php
> +    {
Siehe #1147

2023-11-10 13:29 UTC, j3nsch commented on modules/oai/models/Set/CollectionSets.php
> +        $roleOaiNames = array_column(CollectionRole::fetchAllOaiEnabledRoles(), 'oai_name');
Eigentlich wird hier doch die ganze Logik in **getSets** umgangen. Das heißt wenn wir die Set-Generierung ändern, z.B. einschränken, das müsste hier dupliziert werden. Diese Funktion hier müsste `getSets` verwenden, oder?

2023-11-10 14:05 UTC, haogatyp commented on tests/modules/oai/controllers/IndexControllerTest.php
> +    {
Habe ich so geändert, dass für unbekannte Sets noRecordsMatch geliefert wird.

2023-11-10 14:05 UTC, j3nsch commented on modules/oai/models/Set/CollectionSets.php
> +        $roleOaiNames = array_column(CollectionRole::fetchAllOaiEnabledRoles(), 'oai_name');
Ich hatte vergessen, dass wir hier nur die Namen der Rollen berücksichtigen, nicht die Subsets. Das passiert aber in `getSets` ebenfalls am Anfang, wenn wir einen Mechanismus hinzufügen wollen, der Rollen ausschließt, weil sie von einer anderen Set-Klasse behandelt werden, bräuchten wir eine Funktion wie `getCollectionRoles`, die dann an beiden Stellen verwendet wird.

2023-11-10 15:16 UTC, haogatyp commented on modules/oai/models/Set/CollectionSets.php
> +        $roleOaiNames = array_column(CollectionRole::fetchAllOaiEnabledRoles(), 'oai_name');
Mit Blick auf  z.B. open_access wäre das so. Ich habe es jetzt auf die Verwendung der getSets-Methode umgestellt.

2023-11-17 08:40 UTC, j3nsch commented on tests/library/Application/View/Helper/DcTypeTest.php
> +    public function testDcTypeForDiplom()
Mach mal bitte diese Tests hier mit einem @dataProvider. Beispiele finden sich im Code. Die Testfunktion bekommt dann zwei Parameter, $dcType und $opusType.

2023-11-17 08:56 UTC, haogatyp commented on tests/library/Application/View/Helper/DcTypeTest.php
> +    public function testDcTypeForDiplom()
Das sind aber arrays mit den möglichen Werten, oder?

2023-11-17 09:00 UTC, haogatyp commented on tests/library/Application/View/Helper/DcTypeTest.php
> +    public function testDcTypeForDiplom()
Ah, jetzt habe ich es.

2023-11-17 12:18 UTC, j3nsch commented on tests/library/Application/View/Helper/DcTypeTest.php
>      public function opusTypeToMasterThesisDataProvider()
Is okay, aber ich hätte es trotz allem etwas generische formuliert, z.B. `opusTypeToDcTypeDataProvider`. Es gibt ja nichts was diese Tests wirklich auf MasterThesis beschränken würde, auch wenn das jetzt der Anlass ist.

2023-11-21 16:39 UTC, j3nsch commented
Soll ich mir das anschauen? Was ist der Stand?

2023-11-23 12:48 UTC, merged