OPUSVIER-4289 Switch logging code to LogService
OPUS4/application pull request #345
Opened 2020-08-27 15:31 UTC by kaustabhbarman

2020-08-27 16:00 UTC, j3nsch requested changes
Didn't want to make the comments as review, but it cannot be changed now. Good start. There is at least one more piece code where a `Zend_Log` object is created. It should be mentioned in the ticket, so it is clear it has been seen, but a decision has been made to not changed, because ... (It is actually a usage that does not quite fit `LogService` and we should make a decision whether it needs to be adapted.)

2020-08-27 16:00 UTC, j3nsch commented on library/Application/Update.php
> +        //TODO OPUSVIER-4289 use LogService function to log
Do we really need to change anything here? What would be a good reason?

2020-09-01 18:36 UTC, j3nsch commented on tests/library/Application/Update/ImportHelpFilesTest.php
> +    }
This function needs to call `parent::tearDown()` at the end, because otherwise you disable all tearDown code in the parent classes.

2020-09-03 10:33 UTC, kaustabhbarman commented on tests/library/Application/Update/ImportHelpFilesTest.php
> +    }
Yes right. Will add it.

2020-09-03 15:11 UTC, kaustabhbarman commented
Today, I tried to use the LogService in application. I know we have to configure `application.ini` first. But I would like to do that when we have a better medium of communication (working Mattermost). I have made some changes in the Bootstrap file only so that you can further mention how exactly can we use `LogService` from Opus4-common repo. Other than this, I have found out other places where `Zend_Log` object has been created and put the TODO comment there. Please have a look at the recent commit and let me know how can it be improved.

2020-09-03 15:38 UTC, j3nsch commented on library/Application/Bootstrap.php
> +        $logger = $logService->createLog('translation', null, '%timestamp%: %message%' . PHP_EOL, null);
The `PHP_EOL` should not be necessary. I think `LogService` is handling that. In the end it should be `getLog('translation')` here with all the configuration in `application.ini`.

2020-09-03 15:42 UTC, j3nsch commented on scripts/update_migration/MigrateSeriesCollections.php
> +     * TODO OPUSVIER-4289 Use LogService
This and the other migration one are the usages of `Zend_Log` that do not fit `LogService`. Here the log is being written into the current folder, so using `LogService` would change that behavior. I think we don't want that. So these two need to be mentioned  in the ticket with a reason why we left them.

2020-09-03 15:47 UTC, j3nsch commented on tests/modules/publish/models/FormElementTest.php
> +     * TODO OPUSVIER-4289 Use LogService
Do we really want to use `LogService` here? What is happening here? The class used prevents log message from being written. I have no idea why this is done here, but `LogService` won't improve the situation.

2020-09-03 15:56 UTC, j3nsch commented on library/Application/Bootstrap.php
> +        $logger = $logService->createLog('translation', null, '%timestamp%: %message%' . PHP_EOL, null);
The format should probably contain more information. I think we need the __runId__ so we can match output to requests in the regular log. I do not think the timestamp and the log level are necessary.

2020-09-10 10:11 UTC, j3nsch commented on application/configs/application.ini
> +logging.log.translation.format = '' ; TODO what should be the format?
Make a suggestion

2020-09-10 10:12 UTC, j3nsch commented on application/configs/application.ini
> +; TODO log.level has already been set as WARN
This is a different environment. The INI file has four sections that are used in different situations.

2020-09-10 11:13 UTC, kaustabhbarman commented on application/configs/application.ini
> +logging.log.translation.format = '' ; TODO what should be the format?
I have set the translation format as `'%timestamp% %priorityName% : %message%'` in my latest commit. Didn't include `run ID` as it is only set inside `getDefaultFormat()` which only considers `log.format`.

2020-09-14 06:46 UTC, j3nsch requested changes
Thank you. Looks good. Just some small polishing of comment and formats left.

2020-09-14 06:46 UTC, j3nsch commented on application/configs/application.ini
> +logging.log.translation.format = '%timestamp% %priorityName% (%priority%, ID %runId%): %message%'
I think we can safely remove `%priorityName%` and `%priority%`. It is the same for all translation errors.

2020-09-14 06:46 UTC, j3nsch commented on application/configs/application.ini
> +log.format = '%timestamp% %priorityName% (%priority%, ID %runId%): %message%'
I think we should use this opportunity to remove `%priority%`. I don't see any value in having the number there.

2020-09-14 06:46 UTC, j3nsch commented on application/configs/application.ini
> +logging.log.translation.level = INFO
Why `INFO`?

2020-09-14 06:46 UTC, j3nsch commented on application/configs/application.ini
> +logging.log.translation.level = INFO
Please add a comment for the users to explain what `INFO` means here and what other level might make sense for what purpose (see `Application_Translate`).

2020-09-14 06:46 UTC, j3nsch commented on scripts/update_migration/MigrateSeriesCollections.php
> +     * LogService cannot be used here as the log is being written into the current folder, LogService would change that behaviour.
I think shorter and with OPUSVIER-xxxx reference would be better. Maybe even use TODO, not because we want to fix it later, but it will show up on the radar and we can reconsider later. Or you extend `LogService` so it is possible to override the path and actually use it here. Up to you!

2020-09-14 06:46 UTC, j3nsch commented on tests/support/SimpleBootstrap.php
> +        $logService = LogService::getInstance();
Looks like there was some redundant code before. Good catch! Just looking at it, I didn't notice any differences to the old code in the other Bootstrap, so I guess it should be fine.

2020-09-15 16:07 UTC, kaustabhbarman commented on application/configs/application.ini
> +logging.log.translation.level = INFO
The `DEFAULT_PRIORITY` is set to `INFO`. I checked the `Application_Translate`, where the `logPriority` is set to `Zend_Log::DEBUG`. It would be nice if I have some more context on this. For now, I am changing it to `DEBUG`.

2020-09-16 08:03 UTC, j3nsch requested changes
Just a tiny bit left and two tickets should be done.

I modified two comments. They were good, I just wanted them even shorter and I also wanted to reduce the prominence of the ticket reference. It is just for additional information and not the TODO ticket for this. This is mostly personal taste and not objective.

2020-09-18 05:46 UTC, j3nsch commented on application/configs/application.ini
> +logging.log.translation.level = INFO
A bit confusing to put the info that belongs to `translation.level` right about `log.level`. Setting `log.level` to DEBUG won't enable logging of missing translations. The details are important. Always ask, if it is as easy as possible to understand for the next developer or user looking at it.

2020-09-18 06:20 UTC, j3nsch approved these changes
Okay.

2020-09-18 06:21 UTC, merged

2020-09-18 07:29 UTC, j3nsch commented on tests/support/SimpleBootstrap.php
> +        Zend_Registry::set('LOG_LEVEL', $logLevel);
Yes, I missed that.

2020-09-18 07:31 UTC, j3nsch commented on tests/support/SimpleBootstrap.php
> +        Zend_Registry::set('LOG_LEVEL', $logLevel);
It should not have happened, especially since it broke the build.