OPUSVIER-ISSUE416
OPUS4/application pull request #419
Opened 2021-08-20 16:29 UTC by kaustabhbarman

2021-09-20 13:23 UTC, j3nsch commented on tests/library/Application/Job/CleanTemporariesJobTest.php
> +class CleanTemporaries extends ControllerTestCase
The test class needs to have the same name as the file, so it should be `CleanTemporatiesJobTest`

2021-09-20 13:24 UTC, j3nsch commented on tests/library/Application/Job/CleanTemporariesJobTest.php
> +require_once dirname(__FILE__) . '/../../../scripts/cron/OpusDocumentMock.php';
We don't use `require_once` in our regular unit tests. It should not be necessary.

2021-09-20 13:26 UTC, j3nsch commented on tests/library/Application/Job/CleanTemporariesJobTest.php
> +require_once dirname(__FILE__) . '/../../../scripts/cron/OpusDocumentMock.php';
If you need to move the class `OpusDocumentMock`, do it. We already have folders for classes supporting tests.

2021-09-20 13:26 UTC, j3nsch commented on tests/library/Application/Job/CleanTemporariesJobTest.php
> +require_once dirname(__FILE__) . '/../../../../library/Application/Job/CleanTemporariesJob.php';
Definitely not. Please take a look at the other unit tests.

2021-09-20 13:29 UTC, j3nsch commented on tests/library/Application/Job/CleanTemporariesJobTest.php
> +        $this->setExpectedException(NotFoundException::class);
You need to declare the expected exception before performing the operation that throws it, so switch lines 60 and 61.

2021-09-30 13:47 UTC, j3nsch commented on scripts/cron/cron-send-notification.php
> +$job = new SendNotificationJob();
The name of the class is `Application_Job_SendNotificationJob`.

2021-09-30 13:47 UTC, j3nsch commented on library/Application/Job/SendNotificationJob.php
> +class SendNotificationJob implements JobInterface
The name of the class is `Application_Job_SendNotificationJob`.

2021-10-07 09:05 UTC, j3nsch requested changes
I stop the review without looking at the classes in more detail. At the moment code was just moved. That is fine for now. The classes should have tests, but for some classes, the once that use `Runner` we need to think about what the purpose of each classes is and if the current design makes sense. Are we wrapping a job in a job here. Is it necessary? Why? What next steps should be taken?

2021-10-07 09:05 UTC, j3nsch commented on library/Application/Job/CheckConsistensyJob.php
> +class Application_Job_CheckConsistensyJob implements JobInterface
"Consistency" with a "c" before the "y"

2021-10-08 15:28 UTC, kaustabhbarman commented on Jenkinsfile
> +
It was not intentional. Must have been by mistake.

2021-10-14 15:48 UTC, j3nsch commented
Modified title of PR so it can be understood without effort.

2021-10-21 15:37 UTC, kaustabhbarman commented
> I stop the review without looking at the classes in more detail. At the moment code was just moved. That is fine for now. The classes should have tests, but for some classes, the once that use `Runner` we need to think about what the purpose of each classes is and if the current design makes sense. Are we wrapping a job in a job here. Is it necessary? Why? What next steps should be taken?

In the classes that uses `Runner`, a worker class is being registered first in `Runner` class using `registerWorker()` function. The `run` function of `Runner` fetches jobs, creates new jobs, execute them by calling `work()` function of the worker class and lastly, removes it from the jobs table on success. 
This operation consists of few steps like setting the logger, delay, limit and registering the worker and currently, theses steps are being wrapped in the job class so that they can all be done with a single call. 

In my opinion, as long as we don't want to change some of the arguments like a different delay or limit, this design makes sense. But if we are to make these arguments dynamic, we might as well call each function like `setDelay()` or `setLimit()` instead of wrapping them in another job wrapper and passing these arguments as class parameters.

2021-10-21 17:35 UTC, j3nsch commented on library/Application/Job/CheckWorkspaceFilesJob.php
> +        exit(1);
Exit statements would be bad if we want to execute this class in some other context. There should not be any exit statements in the job classes.

2021-11-10 07:47 UTC, merged