Doi Import
OPUS4/application pull request #976
Opened 2022-11-18 14:07 UTC by bfalkenstein

Adding Crossref based metadata import to publish form

2022-11-29 14:09 UTC, j3nsch requested changes
Danke für den Pull Request. Ich sehe ein paar Probleme, die erst einmal nichts mit der Funktion zu tun haben, aber für die Entwicklung wichtig sind. Am wichtigsten wäre es aber erst einmal herauszufinden warum die editierten Dateien mit Diff als komplett geändert auftauchen und das zu beheben, weil so kein Review möglich ist. Ich vermute es liegt daran, dass die Zeilenenden ersetzt wurden. Wurden die Dateien auf einem Windows System editiert?

2022-11-29 14:09 UTC, j3nsch commented on public/getDoctypes.php
> +<?php
Diese Datei wird definitiv nicht hier bleiben. Das gehört in eine Controller-Klasse, wie die gesamte restliche OPUS 4 Funktionalität. Wir können nicht anfangen für ein paar Sonderfunktionen zusätzliche PHP-Skripte einfach ins "public"-Verzeichnis zu packen. Vor allem unterwandert der direkte Zugriff auf `config.ini` das Konfigurationshandling in OPUS 4. Wenn dort Änderungen vorgenommen werden, müsste man sich immer dran erinnern, dass es ja  noch ein Skript gibt, dass die Dinge anders handhabt. 

Am Besten für diese Funktionalität ein Issue anlegen, mit einer Beschreibung, was als Ausgabe benötigt wird. Dann kann überlegt werden wo der Code hingehört.

2022-11-29 14:09 UTC, j3nsch commented on public/getDoctypes.php
> +?>
Dateien müssen immer mit einem Zeilenumbruch enden. Das signalisiert GitHub zum Glück auch im Diff, weil es immer mal gerne vergessen wird.

2022-11-29 14:09 UTC, j3nsch commented on public/layouts/opus4/js/getDoi.js
> +
Bitte keine leeren Zeilen am Ende von Dateien, mit Ausnahme des letzten Zeilenumbruchs.

2022-11-29 14:17 UTC, j3nsch commented
Im Augenblick ist geplant diese Funktionalität mit in OPUS 4.7.2 aufzunehmen. Momentan wird noch daran gearbeitet diese Version kompatibel mit PHP 8 zu machen. Die dafür notwendigen Änderungen sollten keine Auswirkungen auf den DOI-Import haben. Die neuen Source Code Dateien sollten einen OPUS 4 Lizenz Header bekommen. Darum kann ich mich kümmern.

Wenn die Diff-Probleme mit den editierten Dateien gelöst sind werde ich den PR erst einmal in einen neuen Branch übernehmen, um weitere Änderungen vornehmen zu können.

Es sollte überlegt werden, ob es nicht besser wäre den Request für die Metadaten an einen OPUS 4-Controller zu schicken, der dann eine Request an die Datenquelle absetzt. Auf diese Weise würde der Client-Browser nicht mit einem anderen Server kommunizieren. Über diese Kommunikation müssten ansonsten vermutlich die NutzerInnen informiert werden, da dabei ja auch Daten wie IP-Adressen in die andere Richtung übertragen werden. Wo wird der Source-Server für die Metadaten gehostet? 

Ein Umleitung durch den PHP Code von OPUS 4 auf dem Server hätte auch den Vorteil, dass dort eine Vorverarbeitung stattfinden könnte und der Code leichter durch Unit Tests abdeckbar wäre.

2022-12-05 12:33 UTC, j3nsch commented
Wenn man mit Vagrant eine VM für die OPUS 4 Application hochfährt (`vagrant up`), kann man sich mit `vagrant ssh` in die VM einloggen und hat dort Tools, um den Coding Style zu prüfen. Mit `composer cs-check` wird geprüft, mit `composer cs-fix` können viele Probleme automatisch korrigiert werden. Das korrigiert auch die Zeilenumbrüche.

2022-12-05 12:56 UTC, j3nsch commented on public/layouts/opus4/js/getDoi.js
> +         /* else {
Ist die Idee hier, dass die Datei für einzelne Instanzen angepasst wird?

2022-12-05 13:08 UTC, j3nsch commented
Der Branch ist jetzt auf den aktuellen Stand der Entwicklung für OPUS 4.7.2 aktualisiert. Ich hoffe das verursacht keine Probleme. Es war notwendig, weil weitere Anpassungen im Code notwendig sind, die den aktuellen 4.7.2 Code benötigen. 

Es wäre möglich gewesen den PR in einen Branch zu übernehmen, dort die Aktualisierung durchzuführen und dann einen neuen internen PR anzulegen. Der alte PR wäre dann geschlossen worden und die Conversation hätte dann im neuen PR fortgeführt werden müssen.

2022-12-05 13:11 UTC, bfalkenstein commented on public/layouts/opus4/js/getDoi.js
> +         /* else {
Nein, das ist ein Relikt aus der Entwicklung, das kann weg. Sorry!

2022-12-05 13:55 UTC, bfalkenstein commented
Noch eine Frage/Anmerkung: Für die ganze Funktionalität werden ja mehrere Enrichment-Felder verwendet:

opus_import_data
opus_doi_flag
local_crossrefDocumentType
local_crossrefLicence
local_doiImportPopulated
local_import_origin
conference_title
conference_place

Die Frage ist, ob man die schon im Standard anlegen will, oder ob sie später bei Bedarf (also nur, falls der DOI-Import überhaupt verwendet wird) hinzugefügt werden sollten.

2022-12-05 14:01 UTC, j3nsch commented
> Noch eine Frage/Anmerkung: Für die ganze Funktionalität werden ja mehrere Enrichment-Felder verwendet:
> 
> opus_import_data opus_doi_flag local_crossrefDocumentType local_crossrefLicence local_doiImportPopulated local_import_origin conference_title conference_place
> 
> Die Frage ist, ob man die schon im Standard anlegen will, oder ob sie später bei Bedarf (also nur, falls der DOI-Import überhaupt verwendet wird) hinzugefügt werden sollten.

Das ist eine gute Frage. Wir setzen das mal in #580 fort. Das neue Ticket, #981, werde ich weiter für die grundlegenden Code-Anpassungen für die Übernahme verwenden.

2022-12-12 10:38 UTC, merged